### ISSUE TITLE
Can't create MIPS Big-Endian Emulator

### ISSUE THREAD

**Issue by endeav0r** [unicorn-rs/unicorn-rs#32]
To create a MIPS Big Endian emulator, I need to be able to pass the flags `MODE_32` and `BIG_ENDIAN`. Because [`Mode`](https://docs.rs/unicorn/0.8.0/unicorn/unicorn_const/enum.Mode.html) is a rust enum, I can only pass one of these values. I can only pass `Mode::MODE_32`.

Because [the value of `LITTLE_ENDIAN` is `0`](https://github.com/unicorn-engine/unicorn/blob/master/include/unicorn/unicorn.h#L102), this effectively becomes `MODE_32 | LITTLE_ENDIAN`.

**Comment by endeav0r** [comment]
So this is possible:

```
    let mode = unicorn::Mode::BIG_ENDIAN as i32 | unicorn::Mode::MODE_32 as i32;
    let mode = unsafe { ::std::mem::transmute::<i32, unicorn::Mode>(mode) };
    let emu = CpuMIPS::new(mode)
        .expect("Failed to initialize unicorn engine");
```

But it would be nice if there was a way to accomplish this without having to do an unsafe transmute.

**Comment by ekse** [comment]
Hi, the issue is that Mode should have been defined as a bitflags rather than an enum. I pushed a branch that does this change. Could you test with it to see if works as intended? 

https://github.com/ekse/unicorn-rs/compare/mode-flag?expand=1

**Comment by XVilka** [comment]
So this one can be closed then? Am I right?
